### ISSUE TITLE
error

### ISSUE THREAD

**Issue by itst3ch** [EthanC/Athena#1]
I get an error and I dont know how to fix it! Here is the error:

Athena - Fortnite Item Shop Generator
https://github.com/EthanC/Athena

Traceback (most recent call last):
  File "itemshop.py", line 296, in <module>
    Athena.main(Athena)
  File "itemshop.py", line 20, in main
    initialized = Athena.LoadConfiguration(self)
  File "itemshop.py", line 57, in LoadConfiguration
    configuration = json.loads(Utility.ReadFile(self, "configuration", "json"))
  File "C:\Users\Holden\AppData\Local\Programs\Python\Python37-32\lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Holden\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Holden\AppData\Local\Programs\Python\Python37-32\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 3 column 25 (char 48)

**Comment by EthanC** [comment]
Paste your `configuration.json` file here, without the API keys and tokens.

**Comment by itst3ch** [comment]
{
    "delayStart": 15,
    "supportACreator": "",
    "fnbr": {
        "apiKey": "XXXXXXXXXXXXXXX"
    },
    "twitter": {
        "enabled": true,
        "apiKey": "XXXXXXXXXXXXXXX",
        "apiSecret": "XXXXXXXXXXXXXXX",
        "accessToken": "XXXXXXXXXXXXXX",
        "accessSecret": "XXXXXXXXXXXXXX"
    }

**Comment by EthanC** [comment]
You're missing a closing curly-bracket (`}`) at the end of the file. Copy [configuration_example.json](https://github.com/EthanC/Athena/blob/master/configuration_example.json) again and fill it in without changing any spacing or adding/removing any lines.

**Comment by itst3ch** [comment]
k ty
